### ISSUE TITLE
R code for cnv calling and plots using "gsrc"

### ISSUE THREAD

**Issue by ekarlins** [NCBI-Hackathons/Global_Screening_Arrays#10]
Write R code using the package "gsrc".  Since we have a working pipeline to generate LRR and BAF in PennCNV format, start your code by reading the PennCNV input file into R.  You can find an example file in our repo here "files/pennTest2.txt".

Take this input file and do CNV calling using "gsrc".  Write CNV calls to a file, preferably in bed or bedgraph format.  This will allow for easy comparison with PennCNV output using bedtools or similar, as well as easy upload to UCSC browser for further visualization with genomic context.  Also write code to output some plots of CNV calls.

I'm asking you to do your CNV calling one sample at a time (each input file only has data from one sample).  This may not be possible.  For PennCNV, for example you need to generate a reference file using many samples before you can do CNV calling one sample at a time.  I'm going to have generating the PennCNV reference file as it's own module.  If there is a step like this in "gsrc" we can add this to the same module as the PennCNV reference.  So please split this off into separate code.

Put R code files into the "R/" directory in our repo.  Make a new .R file for each separate task, and clearly define required input files and output files.

**Comment by ngiangre** [comment]
The R script gsrcCNVcalling.R in R/ will take in a directory with the pennTest-like files and an output directory as input and output a bed file with char/start/end/num_probes/avg_signal. No header. Let me know if I should change the input.

I'm working on assigning the copy states as well within the same script. 

The plot features from 'gsrc' require defined synteny blocks which requires extra processing and mapping and things. So all the pretty plots at the end of https://cran.r-project.org/web/packages/gsrc/vignettes/introduction.html won't work without synteny blocks.

**Comment by ekarlins** [comment]
@ngiangre, I had to change the header line for the txt file.  Can you change your code to work with the new header line?
I deleted the old txt file and added "files/201274980046_R04C02.PennCNV_in.txt" to the repo.  It has the new header line.

Thanks!

**Comment by ngiangre** [comment]
Yup, I can change the script to adapt to the new header line

**Comment by ngiangre** [comment]
R script was adapted to new headers, assign cnv state to region if consistent across probes in region, and was tested successfully on ubuntu with

"/opt/R-3.3.1/bin/Rscript gsrcCNVcalling.R /home/ubuntu/ngiangre/Global_Sc
reening_Arrays/files /home/ubuntu/ngiangre/Global_Screening_Arrays/files/output"

outputs bed file with: chr, start, end, number of probes, avg probe value, and deletion (-1)/duplication (+1)/no change (0) status.

Will now work on manuscript and slide describing R cnv calling approach

**Comment by ngiangre** [comment]
updated R script to assign cnv state to cna regions without excessive looping (its faster)

**Comment by ngiangre** [comment]
The gsrc plotting functions are too specific for their data-looking at other functions/packages instead

**Comment by ngiangre** [comment]
Playing with ggplot for plotting of bed files currently

**Comment by ngiangre** [comment]
finished for now. Start new issue later for R plotting/CNV calling
