### ISSUE TITLE
generate PennCNV PFB file

### ISSUE THREAD

**Issue by ekarlins** [NCBI-Hackathons/Global_Screening_Arrays#11]
Write code using the script "compile_pfb.pl", that comes with PennCNV, to generate a PFB file.

PennCNV is installed on our NCI cluster (CCAD/cgemsiii), so it's probably easiest to just run these tests there.  On the cluster this is how you can see the help page for this script:

module load PennCNV/2015-v1.0.3
compile_pfb.pl -h

Please put working code for generating a PFB file in a .sh file in the "scripts" directory in this repo.  i.e. test the code by submitting the bash script to the cluster using qsub.  Point us to the .sh file and close this ticket once you are confident that this code works.

You'll need a number of PennCNV input txt files for this.  I'll start a separate ticket for generating these txt file for testing.  "scripts/gtc2PennCNV.py" can take gtc files and generate these txt files.  I can point you to some gtc files on our NCI cluster if it's easier to keep everything there instead of dealing with data transfer in multiple places.  For testing you probably can just use a small number of txt files (~10-100).

**Comment by slsevilla** [comment]
Having difficulty with the script.

I am unfamiliar with the commands to make sure all of the other data isn't being added to the txt file.

IE: 5990215630  323 drwxr-sr-x   2 karlinser ncicgr_bioinformatics    27456 Mar 21 17:47 /CGF/Bioinformatics/Production/Eric/Projects/NcbiHackathonMar2017/SnakeTest2/PennCnvIn
5981439282 45842 -rw-r--r--

File is text_filelist.sh

**Comment by ekarlins** [comment]
I generated a PFB file, "files/TestPFB.pfb".
Code to generate it was implemented in "scripts/Snakefile_ref_files".  I needed to change the code in "scripts/gtc2PennCNV.py" to alter the header line of hte txt file this script outputs to get this working.
