### ISSUE TITLE
generate PennCNV input txt files for all gtc files available

### ISSUE THREAD

**Issue by ekarlins** [NCBI-Hackathons/Global_Screening_Arrays#12]
Use "scripts/gtc2PennCNV.py" to generate PennCNV input txt files for all (~1000) gtc files available.  This will serve as a test for "scripts/gtc2PennCNV.py" to see potential errors.  These files will also serve as test input for other issues.  See issue #11.

This can be run on our NCI cluster if that makes the most sense.  Or the data is now on our ubuntu AWS server as well, so it can be run there.  Submitting each of these as individual jobs to the cluster should make all of the jobs complete in a few minutes.  Running these one job after another on AWS will be frustrating.

I can point you to gtc files on our NCI cluster if you want to go there, but would rather put that path in an email.

**Comment by slsevilla** [comment]
Generated files successfully with current gtc2PennCNV.py code.

**Comment by ekarlins** [comment]
This worked successfully using Snakemake as well to run it on ~1000 gtc files.
