### ISSUE TITLE
PennCNV HMM file

### ISSUE THREAD

**Issue by ekarlins** [NCBI-Hackathons/Global_Screening_Arrays#17]
Do we need to create an HMM file?

See PennCNV documentation to figure this out, and if so put code to generate this in "scripts" dir.

**Comment by mtbrown22** [comment]
Looks like the HMM file is bundled with PennCNV. We just need to provide the signal intensity files in proper format.

See first paragraph [here](http://penncnv.openbioinformatics.org/en/latest/user-guide/input/)

**Comment by ekarlins** [comment]
@mtbrown22, I think you are right about the HMM file.  That first paragraph is confusing, though.  It also says the PFB and GC Model file are part of the bundle.  Though there are example files for those, the PFB is specific to the array and the GC Model file is specific for the genome build.  So those two really need to be generated.  I think the HMM will work, though.
