### ISSUE TITLE
gtc2PennCNV error - Line 4 in <module>

### ISSUE THREAD

**Issue by slsevilla** [NCBI-Hackathons/Global_Screening_Arrays#18]
In running the gtc2PennCNV file, I got the following error:

[sevillas2@cgemsIII Sam]$ ./bash2.sh
: No such file or directoryF/TempFileSwap/Sam/
Traceback (most recent call last):
  File "/CGF/TempFileSwap/Sam/Hackathon2017/GitRepo/Global_Screening_Arrays/scripts/gtc2PennCNV.py", line 4, in <module>
    from IlluminaBeadArrayFiles import GenotypeCalls, BeadPoolManifest, code2genotype
ImportError: No module named IlluminaBeadArrayFiles
: command not found
: command not found

**Comment by ekarlins** [comment]
Let me know if it's fixed.  I updated the code of gtc2PennCNV.py.

**Comment by ekarlins** [comment]
This still seems to be broken.  Still working on this.

**Comment by ekarlins** [comment]
This works now.  Note that this script will not work for gtc v3 or earlier.
