### ISSUE TITLE
slides for presentation

### ISSUE THREAD

**Issue by ekarlins** [NCBI-Hackathons/Global_Screening_Arrays#19]
We need to have 5 slides to present when we're done.  We should start working on those.

**Comment by ekarlins** [comment]
I think one of the slides should be a table with all of our names and years of bioinformatics experience.  One of the cool things and challenges about our group is that we are all relatively new to the field, but are still able to get a lot done.

Name         |        Years Of Bioinformatics Experience
---------      |       -----------------------------------------
Eric Karlins |                4

**Comment by ngiangre** [comment]
Got it

**Comment by slsevilla** [comment]
@ngiangre  Can you add information on the R portion of the pipline to the PPT? I was thinking the output page would be great for your graphs.

Otherwise, I think it's almost complete. @ekarlins review please.

**Comment by ekarlins** [comment]
Great job on the slides everyone!
