### ISSUE TITLE
PennCNV Connection

### ISSUE THREAD

**Issue by slsevilla** [NCBI-Hackathons/Global_Screening_Arrays#25]
Add as a submodule in the future for users to not need to download .pl. Help to avoid versioning issues.

Located here: https://github.com/WGLab/PennCNV

Information on PennCNV: http://penncnv.openbioinformatics.org/en/latest/user-guide/download/#penncnv-main-package

**Comment by ekarlins** [comment]
PennCNV has C code along with perl scripts.  There's more to installation than just pointing to the repo.  The user needs to install PennCNV on their system.
See installation instructions here:
https://github.com/WGLab/PennCNV/blob/master/docs/user-guide/install.md
