### ISSUE TITLE
teamlogo

### ISSUE THREAD

**Issue by slsevilla** [NCBI-Hackathons/Global_Screening_Arrays#26]
Posted a file with the logo. Let me know what you think.

![logo](https://cloud.githubusercontent.com/assets/20726305/24212774/ca16eebe-0f06-11e7-925d-d0c2c0fb6dda.png)

**Comment by ngiangre** [comment]
au pretty. First thing I see: fire. And it reminds me of volume for some reason. Or copy number level. Same thing. This gets my seal of approval haha

**Comment by ekarlins** [comment]
Looks awesome! Thanks for doing that!!
