### ISSUE TITLE
Two slides about project

### ISSUE THREAD

**Issue by ekarlins** [NCBI-Hackathons/Global_Screening_Arrays#3]
Put together two slides about projects by 12pm today, 3/20/17.

**Comment by ngiangre** [comment]
My permission key was denied

**Comment by ekarlins** [comment]
@slsevilla Can you add these two slides to this repo?  Then we can close this issue.

Thanks!

**Comment by slsevilla** [comment]
[GSA_Day1.pptx](https://github.com/NCBI-Hackathons/Global_Screening_Arrays/files/856814/GSA_Day1.pptx)

**Comment by ekarlins** [comment]
Thanks!  I added to "files" directory on repo too.
