### ISSUE TITLE
create a name and logo for our pipeline

### ISSUE THREAD

**Issue by ekarlins** [NCBI-Hackathons/Global_Screening_Arrays#9]
This can actually have an impact on how widely this is used.  I see our pipeline as be a really generalized way to start with Illumina raw data and go to CNV calls.  This is not specific to any array or even species, so I think we should take the GSA out of our name.

**Comment by ngiangre** [comment]
CNVpipe?

**Comment by ekarlins** [comment]
Looks like that name already exists:
http://www.mybiosoftware.com/cnvpipe-0-82-enable-cnv-meta-analysis.html

**Comment by ekarlins** [comment]
ArrayScan2CNV?

**Comment by mtbrown22** [comment]
EasyCNV? CNVeasy? CommandCNV? SnakeArrayCNV? I like ArrayScan2CNV or Scan2CNV too.

**Comment by slsevilla** [comment]
ArrayScan2CNV is good!

**Comment by ekarlins** [comment]
We decided on "ArrayScan2CNV"
